[build]
  command = "npm run build" # Comando para construir tu aplicación (puede variar según tu proyecto)
  publish = "dist" # Ruta donde se encuentra el resultado de la construcción de tu aplicación
